### ISSUE TITLE
Output in the observation-frame

### ISSUE THREAD

**Issue by astroferreira** [dnarayanan/powderday#90]
Is there a way to define the the distance to the object in the configuration files? If not, is it difficult to achieve something like that? 

I would like, for example, with the same filter get a rest-frame and a observation-frame image.

**Comment by dnarayanan** [comment]
Hi, thanks for checking it out!   

We didn't put a redshift in the config files (other than implicitly via the TCMB) in part to keep things as flexible as possible.  This said, if you'd like a rest and observation frame, it's possible to set this up manually by forcing your filters to be at the redshift you'd want them to be at.  For example, if you wanted something like the `J_2mass.filter` at the rest frame and at some redshift, you could specify the `J_2mass.filter` in the `parameters_master` file, and then create a new filter that was basically the exact same, but with the wavelengths multiplied by the (1+z) that you wanted.

I will leave this open though since this represents an enhancement that would be straight forward to address.    One could imagine in the text subsequent to line 259 to put something that redshifts the filters there.  Though I'm not 100% sure yet if this makes more sense, or giving the user the ultimate control by just setting up dummy filters at the redshift of their interest makes more sense.     Thoughts definitely welcome!

**Comment by astroferreira** [comment]
Thank you @dnarayanan. 

I also checked that you can set a distance to hyperion ModelOutput `get_image()` method, which should account for cosmological dimming. I agree that having ultimate control should be better, it is just different from someone coming with the instrument properties in the setup ski files.
